baseURL = "https://skuyjs.github.io"
languageCode = "en-us"
title = "SkuyJS"
theme = "skuyjs"

[params]
description = "Http server framework for NodeJS"

[params.copyright]
text = "Built with <i class='fas fa-heart'></i> by <a href='https://github.com/hadihammurabi' target='_blank'>@hadihammurabi</a> and <a href='https://github.com/orgs/skuyjs/people' target='_blank'>all contributors</a> for developers"
